### PR TITLE
feat: add $isSync flag

### PR DESCRIPTION
**Pull request by jaulz**
This PR adds a flag to a dispatched action whether it is synced or not. It will help to debug the source of an action and also other middlewares will be able to distinguish these actions.

### CODE REVIEW

**Comment by AOHUA** [comment]
Can you give an example of your use case, not sure about the value of adding this flag?

**Comment by jaulz** [comment]
@AOHUA I have sagas that navigate whenever an update was successful. If I now synchronize these actions to other tabs the navigation will also take place. With this PR I could simply catch these cases:
```js
export function* navigateAfterChanging() {
  while (true) {
    const action = yield take(successAction(UPDATE_PROVIDER))
    if (isActionSynced(action)) {
      continue
    }

    yield call(navigateBack)
  }
}
```

**Comment by jaulz** [comment]
@AOHUA what do you think? 😊

**Comment by jaulz** [comment]
@AOHUA sorry to bother you but could you give me a quick sign if you consider my PRs? If not, we could close them I think and I will check for other possibilities. Thanks!

**Pull request merged**
